apiVersion: v1
kind: Service
metadata:
  name: api-golang-service
  namespace: api-golang
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app: api-golang
