apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
  labels:
    env: app-test
spec:
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      labels:
        env: test
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SECRET_PASSWORD
            value: {{ .Values.senha_do_bd }}
          - name: MY_SECRET_TEST
            value: {{ .Values.segredo_protegido }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
